version: "2"
run:
  go: "1.24"
  modules-download-mode: readonly
  tests: false
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errorlint
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - ireturn
    - makezero
    - mirror
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - wsl
  settings:
    gosec:
      excludes:
        - G404
        - G306
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - data
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - data
      - vendor
      - third_party$
      - builtin$
      - examples$
